.lava-test:
  extends:
    - .ci-run-policy
  stage: test
  variables:
    GIT_STRATEGY: none # testing doesn't build anything from source
    ENV_VARS: "MESA_GLES_VERSION_OVERRIDE=3.0 DEQP_PARALLEL=6"
  script:
    - BUILD_JOB_ID=`cat artifacts/build_job_id.txt`
    - >
      artifacts/generate_lava.py \
        --template artifacts/lava-deqp.yml.jinja2 \
        --base-artifacts-url $CI_PROJECT_URL/-/jobs/$BUILD_JOB_ID/artifacts/raw/artifacts \
        --device-type ${DEVICE_TYPE} \
        --env-vars "${ENV_VARS}" \
        --arch ${ARCH} \
        --deqp-version gles2 \
        --kernel-image-name ${KERNEL_IMAGE_NAME} \
        --kernel-image-type "${KERNEL_IMAGE_TYPE}" \
        --gpu-version ${GPU_VERSION} \
        --boot-method ${BOOT_METHOD} \
        --lava-tags "${LAVA_TAGS}"
    - lava_job_id=`lavacli jobs submit lava-deqp.yml`
    - echo $lava_job_id
    - rm -rf artifacts/*
    - cp lava-deqp.yml artifacts/.
    - lavacli jobs logs $lava_job_id | grep -a -v "{'case':" | tee artifacts/lava-deqp-$lava_job_id.log
    - lavacli jobs show $lava_job_id
    - result=`lavacli results $lava_job_id 0_deqp deqp | head -1`
    - echo $result
    - '[[ "$result" == "pass" ]]'
  artifacts:
    when: always
    paths:
      - artifacts/

.lava-test:armhf:
  variables:
    ARCH: armhf
    KERNEL_IMAGE_NAME: zImage
    KERNEL_IMAGE_TYPE: "type:\ zimage"
    BOOT_METHOD: u-boot
  extends:
    - .lava-test
    - .use-arm_build
  dependencies:
    - meson-armhf
  needs:
    - meson-armhf

.lava-test:arm64:
  variables:
    ARCH: arm64
    KERNEL_IMAGE_NAME: Image
    KERNEL_IMAGE_TYPE: "type:\ image"
    BOOT_METHOD: u-boot
  extends:
    - .lava-test
    - .use-arm_build
  dependencies:
    - meson-arm64
  needs:
    - meson-arm64

panfrost-t720-test:arm64:
  extends: .lava-test:arm64
  variables:
    DEVICE_TYPE: sun50i-h6-pine-h64
    GPU_VERSION: panfrost-t720
  tags:
    - lava-sun50i-h6-pine-h64

panfrost-t760-test:armhf:
  extends: .lava-test:armhf
  variables:
    DEVICE_TYPE: rk3288-veyron-jaq
    GPU_VERSION: panfrost-t760
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
  tags:
    - lava-rk3288-veyron-jaq

panfrost-t860-test:arm64:
  extends: .lava-test:arm64
  variables:
    DEVICE_TYPE: rk3399-gru-kevin
    GPU_VERSION: panfrost-t860
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
  tags:
    - lava-rk3399-gru-kevin

.panfrost-t820-test:arm64:
  extends: .lava-test:arm64
  variables:
    DEVICE_TYPE: meson-gxm-khadas-vim2
    GPU_VERSION: panfrost-t820
    LAVA_TAGS: panfrost
  tags:
    - lava-meson-gxm-khadas-vim2

.lima-test:armhf:
  extends: .lava-test:armhf
  variables:
    DEVICE_TYPE: sun8i-h3-libretech-all-h3-cc
    GPU_VERSION: lima
  tags:
    - lava-sun8i-h3-libretech-all-h3-cc

.lima-test:arm64:
  extends: .lava-test:arm64
  variables:
    DEVICE_TYPE: meson-gxl-s905x-libretech-cc
    GPU_VERSION: lima
  tags:
    - lava-meson-gxl-s905x-libretech-cc
